# Generated by Django 5.0 on 2025-05-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('finance_manager', 'Finance Manager'), ('invoice_manager', 'Invoice Manager'), ('superuser', 'Super User')], default='superuser', max_length=20),
        ),
    ]
