# Generated by Django 5.0 on 2025-06-05 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_cit_declaration_invoice_ebm_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='contract_copy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_order',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.contract'),
        ),
    ]
