# Generated by Django 5.0 on 2025-06-19 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoice_contract_copy_invoice_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='received_by_finance',
            field=models.BooleanField(default=False),
        ),
    ]
