# Generated by Django 5.0 on 2025-08-20 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoice_received_at_invoice_received_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Not Fully Paid', 'Not Fully Paid'), ('Incomplete', 'Incomplete')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicestatushistory',
            name='new_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Not Fully Paid', 'Not Fully Paid'), ('Incomplete', 'Incomplete')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicestatushistory',
            name='previous_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Not Fully Paid', 'Not Fully Paid'), ('Incomplete', 'Incomplete')], max_length=20),
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoice.invoice')),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
